# -*- coding: utf-8 -*-
"""Swapped_Bit_Barrett_in_rebuttal_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noQn-zugaqIiqiehS0rbfRmGSvCvV9U0
"""

import random


def flip_random_bits(binary_str, n):
    """
    Flip `n` random bits in a binary string.
    """
    binary_list = list(binary_str)
    length = len(binary_list)
    positions = random.sample(range(length), n)
    for pos in positions:
        binary_list[pos] = '1' if binary_list[pos] == '0' else '0'
    return ''.join(binary_list)

#############################################################################


def flip_burst_bit(binary_str, n):
    """
    Flip n consecutive bits in a binary string at a random position.

    Args:
    binary_str (str): Input binary string.
    n (int): Number of consecutive bits to flip.

    Returns:
    str: Binary string with n consecutive bits flipped.
    """
    # Convert binary string to a list of characters for mutability
    binary_list = list(binary_str)

    # Get the length of the binary string
    length = len(binary_list)

    # Ensure we can flip n bits
    if n > length:
        raise ValueError("Burst size n cannot be larger than the binary string length.")

    # Choose a random starting position for the burst
    start_pos = random.randint(0, length - n)

    # Flip n consecutive bits starting from start_pos
    for i in range(start_pos, start_pos + n):
        binary_list[i] = '1' if binary_list[i] == '0' else '0'

    # Convert the list back to a string and return it
    return ''.join(binary_list)

####################################################################################

def l_binary(decimal, l):
    """
    Convert a decimal number to a binary string of length `l`.
    """
    binary = bin(decimal)[2:]
    return binary.zfill(l)
#k= random.randint(0, 4)    # Generate an 8-bit random number
def swap_bits(number, pos1, pos2):
    # Extract the bits at the given positions
    bit1 = (number >> pos1) & 1
    bit2 = (number >> pos2) & 1

    # If the bits are different, toggle them
    if bit1 != bit2:
        # Create a bitmask with 1s at pos1 and pos2
        bitmask = (1 << pos1) | (1 << pos2)
        # Toggle the bits using XOR
        number ^= bitmask

    return number

def get_ith_bit(number, i):   # Extract the i^th bit position (0-based)
   return (number >> i) & 1


##################################################################################

def generate_n_bit_random_number(n):
    if n <= 0:
        raise ValueError("Number of bits must be a positive integer.")

    # Generate a random number in the range [2^(n-1), 2^n - 1]
    lower_bound = 1 << (n - 1)  # Equivalent to 2^(n-1)
    upper_bound = (1 << n) - 1  # Equivalent to 2^n - 1

    return random.randint(lower_bound, upper_bound)
######################################################################
def contains_one(arr):
    return 1 if any(arr) else 0
######################################################################

def barrett_bitswapped_wordwise_fault_injection(a, b, n, l, chunk_size, fault_mode,f):
    # Precompute mu = floor(2^k / n), where k is the bit-length of n multiplied by 2
    #k = n.bit_length() * 2
    k = l * 2
    mu = (1 << k) // n  # Equivalent to 2^k // n
    num_chunks = l // chunk_size  # Break `a` and `b` into chunks of `chunk_size` bits
    faults=[0]*num_chunks
    faults_burst=[0]*num_chunks
    only_in_r_faults=[0]*num_chunks
    only_in_r_faults_burst=[0]*num_chunks
    at_faults=[0]*num_chunks
    at_faults_burst=[0]*num_chunks
    #print(f"The total number of chunks {num_chunks}")
    result = 0
    result_fault=0
    only_in_r_result = 0
    only_in_r_result_burst=0
    result_fault_burst=0
    at_result_fault=0
    at_result_fault_burst=0
    a_bin = l_binary(a, l)
    #print(f"a_bin {a_bin} of l {l} size")
    b_bin = l_binary(b, l)
    #print(f"b_bin {b_bin} of l {l} size")
    if fault_mode in {'A', 'AB'}:
      a_faulty = int(flip_random_bits(a_bin, f), 2)
      a_faulty_burst=int(flip_burst_bit(a_bin, f), 2)
    else:
      a_faulty = a
      a_faulty_burst=a
    #print(f"a_faulty is {a_faulty}")
    #print(f"a_faulty_burst is {a_faulty_burst}")
    if fault_mode in {'B', 'AB'}:
        b_faulty = int(flip_random_bits(b_bin, f), 2)
        b_faulty_burst=int(flip_burst_bit(b_bin, f), 2)
    else:
        b_faulty = b
        b_faulty_burst=b
    #print(f"b_faulty is {b_faulty}")
    #print(f"b_faulty_burst is {b_faulty_burst}")
    # Iterate through chunks of `a`
    for i in range(num_chunks):
        aw = (a >> (i * chunk_size)) & ((1 << chunk_size) - 1)
        aw_faulty = (a_faulty >> (i * chunk_size)) & ((1 << chunk_size) - 1)
        aw_faulty_burst = (a_faulty_burst >> (i * chunk_size)) & ((1 << chunk_size) - 1)
        # Iterate through chunks of `b`
        for j in range(num_chunks):
            pos1=i % chunk_size
            pos2=j % chunk_size
            b_chunk = (b >> (j * chunk_size)) & ((1 << chunk_size) - 1)
            b_chunk_faulty = (b_faulty >> (j * chunk_size)) & ((1 << chunk_size) - 1)
            b_chunk_faulty_burst = (b_faulty_burst >> (j * chunk_size)) & ((1 << chunk_size) - 1)
            # Step 1: Compute the product for the current chunks
            aw_swapped=swap_bits(aw, pos1, pos2)
            #print(f"aw_swapped {aw_swapped} at the position pos1 {pos1} and pos2 {pos2}")
            aw_swapped_faulty=swap_bits(aw_faulty, pos1, pos2)
            #print(f"aw_swapped_faulty {aw_swapped_faulty} at the position pos1 {pos1} and pos2 {pos2}")
            aw_swapped_faulty_burst=swap_bits(aw_faulty_burst, pos1, pos2)
            #print(f"aw_swapped_faulty_burst {aw_swapped_faulty_burst} at the position pos1 {pos1} and pos2 {pos2}")
            #print("After swapped aw_swapped: ",aw_swapped)
            c1 = aw * b_chunk
            c=(get_ith_bit(aw, pos1)-get_ith_bit(aw, pos2))*(2**pos1-2**pos2)*b_chunk + (aw_swapped*b_chunk)
            at_c_faulty = int(flip_random_bits(l_binary(c, l), f), 2) # Fault inject in C
            at_c_faulty_burst = int(flip_burst_bit(l_binary(c, l), f), 2)  # Fault inject in C
            if(c1!=c):
              print("break")
              break
            c_faulty=(get_ith_bit(aw_faulty, pos1)-get_ith_bit(aw_faulty, pos2))*(2**pos1-2**pos2)*b_chunk_faulty + (aw_swapped_faulty*b_chunk_faulty)
            c_faulty_burst=(get_ith_bit(aw_faulty_burst, pos1)-get_ith_bit(aw_faulty_burst, pos2))*(2**pos1-2**pos2)*b_chunk_faulty_burst + (aw_swapped_faulty_burst*b_chunk_faulty_burst)

            # Align the result by shifting according to the chunk positions
            c <<= (i + j) * chunk_size
            at_c_faulty <<= (i + j) * chunk_size
            at_c_faulty_burst <<= (i + j) * chunk_size
            c_faulty <<= (i + j) * chunk_size
            c_faulty_burst <<= (i + j) * chunk_size

            # Step 2: Compute q = floor(c * mu / 2^k) (Barrett pre-reduction)
            q = (c * mu) >> k
            at_q_faulty = (at_c_faulty * mu) >> k
            at_q_faulty_burst = (at_c_faulty_burst * mu) >> k
            q_faulty = (c_faulty * mu) >> k
            q_faulty_burst = (c_faulty_burst * mu) >> k

            # Step 3: Compute r = c - q * n
            r = c - q * n   #ORIGINAL
            only_in_r_faulty = int(flip_random_bits(l_binary(r, l), f), 2) # RANDOM FAULT IN R
            only_in_r_faulty_burst = int(flip_burst_bit(l_binary(r, l), f), 2) # BURST FAULT IN R
            at_r_faulty = at_c_faulty - at_q_faulty * n # RANDOM FAULT IN C
            at_r_faulty_burst = at_c_faulty_burst - at_q_faulty_burst * n # BURST FAULT IN C
            r_faulty = c_faulty - q_faulty * n # RANDOM FAULT IN A/B/AB
            r_faulty_burst = c_faulty_burst - q_faulty_burst * n # BURST FAULT IN A/B/AB
            # Step 4: Reduce r modulo n if necessary
            if r >= n:
                r -= n
            elif r < 0:  # Handle negative values ORIGINAL
                r += n

            if only_in_r_faulty >= n:
                only_in_r_faulty -= n
            elif only_in_r_faulty < 0:  # Handle negative values RANDOM FAULT IN R
                only_in_r_faulty += n

            if only_in_r_faulty_burst >= n:
                only_in_r_faulty_burst -= n
            elif only_in_r_faulty_burst < 0:  # Handle negative values BURST FAULT IN R
                only_in_r_faulty_burst += n

            if r_faulty >= n:
                r_faulty -= n
            elif r_faulty < 0:  # Handle negative values  RANDOM FAULT IN A/B/AB
                r_faulty += n

            if r_faulty_burst >= n:
                r_faulty_burst -= n
            elif r_faulty_burst < 0:  # Handle negative values BURST FAULT IN A/B/AB
                r_faulty_burst += n

            if at_r_faulty >= n:
                at_r_faulty-= n
            elif at_r_faulty< 0:  # Handle negative values  RANDOM FAULT IN C
                at_r_faulty += n

            if at_r_faulty_burst >= n:
                at_r_faulty_burst -= n
            elif at_r_faulty_burst < 0:  # Handle negative values BURST FAULT IN C
                at_r_faulty_burst += n

            # Accumulate the reduced result
            result += r   # ORIGINAL RESULT
            only_in_r_result += only_in_r_faulty # RANDOM FAULT RESULT IN R
            only_in_r_result_burst += only_in_r_faulty_burst # BURST FAULT RESULT IN R
            result_fault +=r_faulty # RANDOM FAULT RESULT IN A/B/AB
            result_fault_burst  +=r_faulty_burst # BURST FAULT RESULT IN A/B/AB
            at_result_fault +=at_r_faulty  # RANDOM FAULT RESULT IN C
            at_result_fault_burst  +=at_r_faulty_burst  # BURST FAULT RESULT IN C


            # Reduce the accumulated result modulo n
            if result >= n:
                result -= n     # ORIGINAL RESULT
            if only_in_r_result >= n:
                only_in_r_result -= n  # RANDOM FAULT RESULT IN R
            if only_in_r_result_burst >= n:
                only_in_r_result_burst -= n  # BURST FAULT RESULT IN R
            if result_fault >= n:  # RANDOM FAULT RESULT IN A/B/AB
                result_fault -= n
            if result_fault_burst >= n:  # BURST FAULT RESULT IN A/B/AB
                result_fault_burst -= n
            if at_result_fault >= n:  # RANDOM FAULT RESULT IN C
                at_result_fault -= n
            if at_result_fault_burst >= n:    # RANDOM FAULT RESULT IN C
                at_result_fault_burst -= n

        fault_detected=result!=result_fault   # RANDOM FAULT RESULT IN A/B/AB
        fault_detected_burst=result!=result_fault_burst   # BURST FAULT RESULT IN A/B/AB
        only_in_r_fault_detected=result!=only_in_r_result  # RANDOM FAULT RESULT IN R
        only_in_r_fault_detected_burst=result!=only_in_r_result_burst # BURST FAULT RESULT IN R
        at_fault_detected=result!=at_result_fault  # RANDOM FAULT RESULT IN C
        at_fault_detected_burst=result!=at_result_fault_burst  # BURST FAULT RESULT IN C
        if(fault_detected):
         faults[i]=1           # RANDOM FAULT RESULT IN A/B/AB
        if(fault_detected_burst):
         faults_burst[i]=1     # BURST FAULT RESULT IN A/B/AB
        if(only_in_r_fault_detected):
         only_in_r_faults[i]=1            # RANDOM FAULT RESULT IN R
        if(only_in_r_fault_detected_burst):
         only_in_r_faults_burst[i]=1       # BURST FAULT RESULT IN R
        if(at_fault_detected):
         at_faults[i]=1                   # RANDOM FAULT RESULT IN C
        if(at_fault_detected_burst):
         at_faults_burst[i]=1             # BURST FAULT RESULT IN C
    fault = contains_one(faults)
    fault_burst = contains_one(faults_burst)
    only_in_r_fault = contains_one(only_in_r_faults)
    only_in_r_fault_burst = contains_one(only_in_r_faults_burst)
    at_fault = contains_one(at_faults)
    at_fault_burst = contains_one(at_faults_burst)

    return result, result_fault, fault, fault_burst, only_in_r_fault, only_in_r_fault_burst, at_fault, at_fault_burst

#############################################################################
def different_mode_different_wordsize(l, w, fault_mode,f,N):
  t_count=0
  t_count_burst=0
  f_count=0
  f_count_burst=0
  only_in_r_t_count=0
  only_in_r_f_count=0
  only_in_r_t_count_burst=0
  only_in_r_f_count_burst=0
  at_t_count=0
  at_t_count_burst=0
  at_f_count=0
  at_f_count_burst=0
  for i in range(N):
    a=generate_n_bit_random_number(l)
    #print(f"The first number a is {a}")
    b=generate_n_bit_random_number(l)
    #print(f"The Second number b is {b}")
    #pos1=random.randint(0, l-1)
    #pos2=random.randint(0, l-1)
    #print(f"The original result is {(a*b)%n}")
    #result, result_fault, fault_detected, fault_detected_burst=barrett_bitswapped_wordwise_fault_injection(a, b, n, l, w, fault_mode,f, pos1, pos2)
    result, result_fault, fault_detected, fault_detected_burst, only_in_r_fault, only_in_r_fault_burst, at_fault_detected, at_fault_detected_burst=barrett_bitswapped_wordwise_fault_injection(a, b, n, l, w, fault_mode,f)
    #print(f"Result: {result}, Faulty Result: {result_fault}, Fault Detected: {fault_detected}")
    if(fault_detected==True):    # RANDOM FAULT IN A/B/AB
     t_count +=1
    else:
     f_count +=1

    if(fault_detected_burst==True):    # BURST FAULT IN A/B/AB
     t_count_burst +=1
    else:
     f_count_burst +=1

    if(only_in_r_fault==True):    # RANDOM FAULT IN R
     only_in_r_t_count +=1
    else:
     only_in_r_f_count +=1

    if(only_in_r_fault_burst==True): # BURST FAULT IN R
     only_in_r_t_count_burst +=1
    else:
     only_in_r_f_count_burst +=1


    if(at_fault_detected==True): # RANDOM FAULT IN C
     at_t_count +=1
    else:
     at_f_count +=1

    if(at_fault_detected_burst==True):  # BURST FAULT IN C
     at_t_count_burst +=1
    else:
     at_f_count_burst +=1




  print(f"The success rate to detect RANDOM BIT fault inject is : {(t_count/N)*100}")
  print(f"The failure rate to not detect  RANDOM BIT fault inject is : : {(f_count/N)*100}")
  print(f"The success rate to detect BURST BIT fault inject is : {(t_count_burst/N)*100}")
  print(f"The failure rate to not detect BURST BIT fault inject is : : {(f_count_burst/N)*100}")
  print()
  print()

  print(f"The success rate to detect RANDOM BIT in C fault inject is : {(at_t_count/N)*100}")
  print(f"The failure rate to not detect  RANDOM BIT in C fault inject is : : {(at_f_count/N)*100}")
  print(f"The success rate to detect BURST BIT in C fault inject is : {(at_t_count_burst/N)*100}")
  print(f"The failure rate to not detect BURST BIT in C fault inject is : : {(at_f_count_burst/N)*100}")
  print()
  print()

  print(f"The success rate to detect RANDOM BIT fault ONLY IN R inject is : {(only_in_r_t_count/N)*100}")
  print(f"The failure rate to not detect  RANDOM BIT fault ONLY IN R inject is : : {(only_in_r_f_count/N)*100}")
  print(f"The success rate to detect BURST BIT ONLY IN R fault inject is : {(only_in_r_t_count_burst/N)*100}")
  print(f"The failure rate to not detect BURST BIT fault ONLY IN R inject is : : {(only_in_r_f_count_burst/N)*100}")
  print()
  print()




# Example usage
N=1000000   # Number of experimental input
if N > 1500000:  # Example threshold.
    raise ValueError("Input is too large, please enter a smaller value.")
n = 3329  # Modulus
#n = 8380417  # Modulus
l=32   #lenth of binary bits
w= 8
f=11
print(f"Fault inject in a: ")
print()
fault_mode='A'  # inject faults in 'a'
#fault_mode='B'  # inject faults in 'b'
#fault_mode='AB'  # inject faults in both 'a' and 'b'
different_mode_different_wordsize(l, w, fault_mode,f, N)
print()
print(f"Fault inject in b: ")
print()
fault_mode='B'  # inject faults in 'b'
different_mode_different_wordsize(l, w, fault_mode,f, N)
print()
print(f"Fault inject both in a and b: ")
print()
fault_mode='AB'  # inject faults in both 'a' and 'b'
different_mode_different_wordsize(l, w, fault_mode,f, N)
print()
print(f"No Fault inject both in a and b: ")
print()
fault_mode='C'  # inject faults in both 'a' and 'b'
different_mode_different_wordsize(l, w, fault_mode,f, N)

